 //jshint esversion:8
/*global require*/
(() => {
  try {
  let langsv = {
    md: "markdown",
    js: "javascript",
    mjs: "nodejs",
    cjs: "nodejs",
    ts: "typescript",
    html: "html5",
    htm: "html5",
    css: "css3",
    java: "java",
    sh: "bash",
    c: "c",
    cpp: "cplusplus",
    cs: "csharp",
    h: "objectivec",
    m: "objectivec",
    less: "less",
    scss: "sass",
    sass: "sass",
    mpy: "python",
    py: "python",
    cli: "clojure",
    cljs: "clojurescript",
    cljc: "clojurescript",
    clj: "clojurescript",
    edn: "clojure",
    rb: "ruby",
    rs: "rust",
    rlib: "rust",
    php: "php",
    travis: "travis",
    yml: "travis",
    COFFEE: "coffescript",
    hs: "haskell",
    hx: "haxe",
    hxml: "haxe",
    json: "javascript",
    xml: "",
    nix: "nixos",
  };
  let langscm = {
    1: "Troff",
    2: "Troff",
    3: "Troff",
    4: "Troff",
    5: "Troff",
    6: "Troff",
    7: "Troff",
    8: "Troff",
    9: "Troff",
    c: "C",
    h: "C",
    ino: "C",
    cpp: "C++",
    "c++": "C++",
    cc: "C++",
    cxx: "C++",
    hpp: "C++",
    "h++": "C++",
    hh: "C++",
    hxx: "C++",
    cql: "CQL",
    css: "CSS",
    html: "HTML",
    htm: "HTML",
    handlebars: "HTML",
    hbs: "HTML",
    java: "Java",
    js: "JavaScript",
    mjs: "JavaScript",
    cjs: "JavaScript",
    json: "JSON",
    map: "JSON",
    jsx: "JSX",
    md: "Markdown",
    markdown: "Markdown",
    mkd: "Markdown",
    php: "PHP",
    php3: "PHP",
    php4: "PHP",
    php5: "PHP",
    php7: "PHP",
    phtml: "PHP",
    pls: "PLSQL",
    BUILD: "Python",
    bzl: "Python",
    py: "Python",
    pyw: "Python",
    rs: "Rust",
    sql: "SQL",
    tsx: "TSX",
    ts: "TypeScript",
    wat: "WebAssembly",
    wast: "WebAssembly",
    xml: "XML",
    xsl: "XML",
    xsd: "XML",
    svg: "XML",
    dyalog: "APL",
    apl: "APL",
    asc: "PGP",
    pgp: "PGP",
    sig: "SML",
    asn: "ASN.1",
    asn1: "ASN.1",
    b: "Brainfuck",
    bf: "Brainfuck",
    cob: "Cobol",
    cpy: "Cobol",
    cs: "C#",
    clj: "Clojure",
    cljc: "Clojure",
    cljx: "Clojure",
    cljs: "ClojureScript",
    gss: "Closure Stylesheets (GSS)",
    cmake: "CMake",
    "cmake.in": "CMake",
    coffee: "CoffeeScript",
    cl: "Common Lisp",
    lisp: "Common Lisp",
    el: "Common Lisp",
    cyp: "Cypher",
    cypher: "Cypher",
    pyx: "Cython",
    pxd: "Cython",
    pxi: "Cython",
    cr: "Crystal",
    d: "D",
    dart: "Dart",
    diff: "diff",
    patch: "diff",
    dtd: "DTD",
    dylan: "Dylan",
    dyl: "Dylan",
    intr: "Dylan",
    ecl: "ECL",
    edn: "edn",
    e: "Eiffel",
    elm: "Elm",
    erl: "Erlang",
    factor: "Factor",
    forth: "Forth",
    fth: "Forth",
    "4th": "Forth",
    f: "Fortran",
    for: "Fortran",
    f77: "Fortran",
    f90: "Fortran",
    f95: "Fortran",
    fs: "F#",
    s: "Gas",
    feature: "Gherkin",
    go: "Go",
    groovy: "Groovy",
    gradle: "Groovy",
    hs: "Haskell",
    hx: "Haxe",
    hxml: "HXML",
    pro: "IDL",
    jsonld: "JSON-LD",
    j2: "Jinja2",
    jinja: "Jinja2",
    jinja2: "Jinja2",
    jl: "Julia",
    kt: "Kotlin",
    less: "LESS",
    ls: "LiveScript",
    lua: "Lua",
    mrc: "mIRC",
    m: "Octave",
    nb: "Mathematica",
    wl: "Mathematica",
    wls: "Mathematica",
    mo: "Modelica",
    mps: "MUMPS",
    mbox: "Mbox",
    nsh: "NSIS",
    nsi: "NSIS",
    nt: "NTriples",
    nq: "NTriples",
    mm: "Objective-C++",
    ml: "OCaml",
    mli: "OCaml",
    mll: "OCaml",
    mly: "OCaml",
    oz: "Oz",
    p: "Pascal",
    pas: "Pascal",
    pl: "Perl",
    pm: "Perl",
    pig: "Pig",
    ps1: "PowerShell",
    psd1: "PowerShell",
    psm1: "PowerShell",
    properties: "Properties files",
    ini: "Properties files",
    in: "Properties files",
    proto: "ProtoBuf",
    pp: "Puppet",
    q: "Q",
    r: "R",
    R: "R",
    spec: "RPM Spec",
    rb: "Ruby",
    sas: "SAS",
    sass: "Sass",
    scala: "Scala",
    scm: "Scheme",
    ss: "Scheme",
    scss: "SCSS",
    sh: "Shell",
    ksh: "Shell",
    bash: "Shell",
    siv: "Sieve",
    sieve: "Sieve",
    st: "Smalltalk",
    sml: "SML",
    fun: "SML",
    smackspec: "SML",
    rq: "SPARQL",
    sparql: "SPARQL",
    nut: "Squirrel",
    styl: "Stylus",
    swift: "Swift",
    text: "LaTeX",
    ltx: "LaTeX",
    tex: "LaTeX",
    v: "Verilog",
    sv: "SystemVerilog",
    svh: "SystemVerilog",
    tcl: "Tcl",
    textile: "Textile",
    toml: "TOML",
    ttcn: "TTCN",
    ttcn3: "TTCN",
    ttcnpp: "TTCN",
    cfg: "TTCN_CFG",
    ttl: "Turtle",
    webidl: "Web IDL",
    vb: "VB.NET",
    vbs: "VBScript",
    vtl: "Velocity",
    vhd: "VHDL",
    vhdl: "VHDL",
    xy: "XQuery",
    xquery: "XQuery",
    ys: "Yacas",
    yaml: "YAML",
    yml: "YAML",
    z80: "Z80",
    mscgen: "MscGen",
    mscin: "MscGen",
    msc: "MscGen",
    xu: "Xù",
    msgenny: "MsGenny",
  };
  let detectMime = (fn) => {
    //grab last part of filename
    let fnExt;
    if (fn.includes(".cmake.in")) fnExt = "cmake.in";
    else fnExt = fn.split(".").reverse()[0];
    let fnMode = langscm[fnExt];
    console.log(fnMode,fn,fnExt);
    let mimetypes = {
      "text/apl": "APL",
      "application/pgp": "PGP",
      "application/pgp-encrypted": "PGP",
      "application/pgp-keys": "PGP",
      "application/pgp-signature": "PGP",
      "text/x-ttcn-asn": "ASN.1",
      "text/x-asterisk": "Asterisk",
      "text/x-brainfuck": "Brainfuck",
      "text/x-csrc": "C",
      "text/x-c++src": "C++",
      "text/x-cobol": "Cobol",
      "text/x-csharp": "C#",
      "text/x-clojure": "Clojure",
      "text/x-clojurescript": "ClojureScript",
      "text/x-gss": "Closure Stylesheets (GSS)",
      "text/x-cmake": "CMake",
      "application/vnd.coffeescript": "CoffeeScript",
      "text/coffeescript": "CoffeeScript",
      "text/x-coffeescript": "CoffeeScript",
      "text/x-common-lisp": "Common Lisp",
      "application/x-cypher-query": "Cypher",
      "text/x-cython": "Cython",
      "text/x-crystal": "Crystal",
      "text/css": "CSS",
      "text/x-cassandra": "CQL",
      "text/x-d": "D",
      "application/dart": "Dart",
      "text/x-dart": "Dart",
      "text/x-diff": "diff",
      "text/x-django": "Django",
      "text/x-dockerfile": "Dockerfile",
      "application/xml-dtd": "DTD",
      "text/x-dylan": "Dylan",
      "text/x-ebnf": "EBNF",
      "text/x-ecl": "ECL",
      "application/edn": "edn",
      "text/x-eiffel": "Eiffel",
      "text/x-elm": "Elm",
      "application/x-ejs": "Embedded JavaScript",
      "application/x-erb": "Embedded Ruby",
      "text/x-erlang": "Erlang",
      "text/x-esper": "Esper",
      "text/x-factor": "Factor",
      "text/x-fcl": "FCL",
      "text/x-forth": "Forth",
      "text/x-fortran": "Fortran",
      "text/x-fsharp": "F#",
      "text/x-gas": "Gas",
      "text/x-feature": "Gherkin",
      "text/x-gfm": "GitHub Flavored Markdown",
      "text/x-go": "Go",
      "text/x-groovy": "Groovy",
      "text/x-haml": "HAML",
      "text/x-haskell": "Haskell",
      "text/x-literate-haskell": "Haskell (Literate)",
      "text/x-haxe": "Haxe",
      "text/x-hxml": "HXML",
      "application/x-aspx": "ASP.NET",
      "text/html": "HTML",
      "message/http": "HTTP",
      "text/x-idl": "IDL",
      "text/x-pug": "Pug",
      "text/x-java": "Java",
      "application/x-jsp": "Java Server Pages",
      "text/javascript": "JavaScript",
      "text/ecmascript": "JavaScript",
      "application/javascript": "JavaScript",
      "application/x-javascript": "JavaScript",
      "application/ecmascript": "JavaScript",
      "application/json": "JSON",
      "application/x-json": "JSON",
      "application/ld+json": "JSON-LD",
      "text/jsx": "JSX",
      "text/jinja2": "Jinja2",
      "text/x-julia": "Julia",
      "text/x-kotlin": "Kotlin",
      "text/x-less": "LESS",
      "text/x-livescript": "LiveScript",
      "text/x-lua": "Lua",
      "text/x-markdown": "Markdown",
      "text/mirc": "mIRC",
      "text/x-mariadb": "MariaDB SQL",
      "text/x-mathematica": "Mathematica",
      "text/x-modelica": "Modelica",
      "text/x-mumps": "MUMPS",
      "text/x-mssql": "MS SQL",
      "application/mbox": "mbox",
      "text/x-mysql": "MySQL",
      "text/x-nginx-conf": "Nginx",
      "text/x-nsis": "NSIS",
      "application/n-triples": "NTriples",
      "application/n-quads": "NTriples",
      "text/n-triples": "NTriples",
      "text/x-objectivec": "Objective-C",
      "text/x-objectivec++": "Objective-C++",
      "text/x-ocaml": "OCaml",
      "text/x-octave": "Octave",
      "text/x-oz": "Oz",
      "text/x-pascal": "Pascal",
      "null": "PEG.js",
      "text/x-perl": "Perl",
      "text/x-php": "PHP",
      "application/x-httpd-php": "PHP",
      "application/x-httpd-php-open": "PHP",
      "text/x-pig": "Pig",
      "text/plain": "Plain Text",
      "text/x-plsql": "PLSQL",
      "text/x-pgsql": "PostgreSQL",
      "application/x-powershell": "PowerShell",
      "text/x-properties": "Properties files",
      "text/x-protobuf": "ProtoBuf",
      "text/x-python": "Python",
      "text/x-puppet": "Puppet",
      "text/x-q": "Q",
      "text/x-rsrc": "R",
      "text/x-rst": "reStructuredText",
      "text/x-rpm-changes": "RPM Changes",
      "text/x-rpm-spec": "RPM Spec",
      "text/x-ruby": "Ruby",
      "text/x-rustsrc": "Rust",
      "text/x-sas": "SAS",
      "text/x-sass": "Sass",
      "text/x-scala": "Scala",
      "text/x-scheme": "Scheme",
      "text/x-scss": "SCSS",
      "text/x-sh": "Shell",
      "application/x-sh": "Shell",
      "application/sieve": "Sieve",
      "text/x-slim": "Slim",
      "application/x-slim": "Slim",
      "text/x-stsrc": "Smalltalk",
      "text/x-smarty": "Smarty",
      "text/x-solr": "Solr",
      "text/x-sml": "SML",
      "text/x-soy": "Soy",
      "application/sparql-query": "SPARQL",
      "text/x-spreadsheet": "Spreadsheet",
      "text/x-sql": "SQL",
      "text/x-sqlite": "SQLite",
      "text/x-squirrel": "Squirrel",
      "text/x-styl": "Stylus",
      "text/x-swift": "Swift",
      "text/x-stex": "sTeX",
      "text/x-latex": "LaTeX",
      "text/x-systemverilog": "SystemVerilog",
      "text/x-tcl": "Tcl",
      "text/x-textile": "Textile",
      "text/x-tiddlywiki": "TiddlyWiki",
      "text/tiki": "Tiki wiki",
      "text/x-toml": "TOML",
      "text/x-tornado": "Tornado",
      "text/troff": "troff",
      "text/x-ttcn": "TTCN",
      "text/x-ttcn-cfg": "TTCN_CFG",
      "text/turtle": "Turtle",
      "application/typescript": "TypeScript",
      "text/typescript-jsx": "TypeScript-JSX",
      "text/x-twig": "Twig",
      "text/x-webidl": "Web IDL",
      "text/x-vb": "VB.NET",
      "text/vbscript": "VBScript",
      "text/velocity": "Velocity",
      "text/x-verilog": "Verilog",
      "text/x-vhdl": "VHDL",
      "script/x-vue": "Vue.js Component",
      "text/x-vue": "Vue.js Component",
      "application/xml": "XML",
      "text/xml": "XML",
      "application/xquery": "XQuery",
      "text/x-yacas": "Yacas",
      "text/x-yaml": "YAML",
      "text/yaml": "YAML",
      "text/x-z80": "Z80",
      "text/x-mscgen": "mscgen",
      "text/x-xu": "xu",
      "text/x-msgenny": "msgenny",
      "text/webassembly": "WebAssembly"
    };
    let mime = [Object.keys(mimetypes),Object.values(mimetypes)];
    for (let v = 0; v < mime[0].length;v++) {
      if (mime[1][v] == fnMode) return mime[0][v];
    }
  };
  require.addMod("@Fe2/mime", {
    detectMime
  });
  } catch(e) {
    alert(e);
  }
})();